"""
Converts EPA GHGRP yearly summary CSV into Supabase seed SQL.

Downloads:
  https://www.epa.gov/ghgreporting/data-sets
  → "GHG Reporting Program - Facility Level Information"

Usage:
  python scripts/prepare_epa_data.py data/ghgp_data.csv

Outputs:
  supabase/seed_facilities.sql
  supabase/seed_reports.sql
  seed_data.json
"""

import csv
import json
import random
import sys
import os

# Column names vary across EPA yearly exports — list most common variants
COL_LAT        = ["LATITUDE", "latitude", "Latitude"]
COL_LNG        = ["LONGITUDE", "longitude", "Longitude"]
COL_EMISSIONS  = ["TOTAL REPORTED DIRECT EMISSIONS", "GHG QUANTITY (METRIC TONS CO2e)",
                   "Total reported direct emissions", "total_reported_direct_emissions"]
COL_FACILITY   = ["FACILITY NAME", "Facility Name", "facility_name"]
COL_ORG        = ["PARENT COMPANIES", "REPORTING NAME", "Parent Companies", "Reporting Name"]
COL_INDUSTRY   = ["INDUSTRY TYPE (SUBPARTS)", "INDUSTRY TYPE", "Industry Type"]
COL_FACID      = ["FACILITY ID", "Facility ID", "facility_id"]
COL_STATE      = ["STATE", "State", "state"]
COL_COUNTY     = ["COUNTY", "County", "county"]
COL_STATE_FIPS = ["STATE FIPS CODE", "State FIPS Code", "state_fips_code"]


def first(row, candidates, default=""):
    for c in candidates:
        if c in row and row[c].strip():
            return row[c].strip()
    return default


def esc(s):
    return s.replace("'", "''")


def prepare(input_csv, output_dir="supabase", sample_size=50, min_emissions=25000):
    facilities = []
    with open(input_csv, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            lat_raw       = first(row, COL_LAT)
            lng_raw       = first(row, COL_LNG)
            emissions_raw = first(row, COL_EMISSIONS)
            if not (lat_raw and lng_raw and emissions_raw):
                continue
            try:
                lat       = float(lat_raw)
                lng       = float(lng_raw)
                emissions = int(float(emissions_raw.replace(",", "")))
            except ValueError:
                continue
            if emissions < min_emissions:
                continue
            if not (-90 <= lat <= 90) or not (-180 <= lng <= 180):
                continue
            facilities.append({
                "epa_facility_id": first(row, COL_FACID),
                "facility_name":   first(row, COL_FACILITY, "Unknown Facility"),
                "org_name":        first(row, COL_ORG,     "Unknown Organization"),
                "industry_type":   first(row, COL_INDUSTRY, "Other"),
                "lat":             lat,
                "lng":             lng,
                "baseline_emissions": emissions,
                "state":           first(row, COL_STATE),
                "county":          first(row, COL_COUNTY),
                "state_fips":      first(row, COL_STATE_FIPS),
            })

    if not facilities:
        print("No facilities parsed — check column names in your CSV.")
        sys.exit(1)

    # Sample across states for geographic diversity
    by_state = {}
    for f in facilities:
        by_state.setdefault(f["state"], []).append(f)

    sampled = []
    per_state = max(1, sample_size // max(len(by_state), 1))
    for st in sorted(by_state):
        sampled.extend(random.sample(by_state[st], min(per_state, len(by_state[st]))))
    sampled = sampled[:sample_size]

    # Build SQL
    sql_facilities = [
        "-- Generated by scripts/prepare_epa_data.py from EPA GHGRP data",
        "-- Source: https://www.epa.gov/ghgreporting/data-sets",
        "",
    ]
    sql_reports = [
        "-- Generated emission reports (synthetic multi-year variance on real baselines)",
        "",
    ]

    for i, f in enumerate(sampled, 1):
        sql_facilities.append(
            f"INSERT INTO facilities"
            f" (org_name, facility_name, industry_type, location, baseline_emissions,"
            f"  reduction_target, epa_facility_id, state_code, county)"
            f" VALUES"
            f" ('{esc(f['org_name'])}', '{esc(f['facility_name'])}', '{esc(f['industry_type'])}',"
            f"  ST_MakePoint({f['lng']}, {f['lat']})::geography,"
            f"  {f['baseline_emissions']}, 20,"
            f"  '{esc(f['epa_facility_id'])}', '{esc(f['state_fips'])}', '{esc(f['county'])}');"
        )
        for year in ["2021", "2022", "2023"]:
            # Realistic variance: trending toward reduction over time
            offsets = {"2021": random.uniform(-0.08, 0.12),
                       "2022": random.uniform(-0.12, 0.08),
                       "2023": random.uniform(-0.18, 0.05)}
            co2 = max(0, int(f["baseline_emissions"] * (1 + offsets[year])))
            target = int(f["baseline_emissions"] * 0.80)
            meets = co2 <= target
            is_red = co2 <= f["baseline_emissions"]
            pct = abs(round((co2 - f["baseline_emissions"]) / f["baseline_emissions"] * 100, 2))
            sql_reports.append(
                f"INSERT INTO emission_reports"
                f" (facility_id, co2_tonnes, period, meets_target, percent_change, is_reduction)"
                f" VALUES ({i}, {co2}, '{year}', {str(meets).lower()}, {pct}, {str(is_red).lower()});"
            )

    os.makedirs(output_dir, exist_ok=True)
    with open(os.path.join(output_dir, "seed_facilities.sql"), "w") as out:
        out.write("\n".join(sql_facilities) + "\n")
    with open(os.path.join(output_dir, "seed_reports.sql"), "w") as out:
        out.write("\n".join(sql_reports) + "\n")
    with open("seed_data.json", "w") as out:
        json.dump(sampled, out, indent=2)

    print(f"✓ {len(sampled)} facilities parsed from {len(facilities)} total (>={min_emissions} tCO2e)")
    print(f"✓ {len(sampled) * 3} emission reports generated (2021-2023)")
    print(f"✓ Output: {output_dir}/seed_facilities.sql, {output_dir}/seed_reports.sql, seed_data.json")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/prepare_epa_data.py <path/to/ghgp_data.csv>")
        sys.exit(1)
    prepare(sys.argv[1])
